name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username pacanimal --password-stdin
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pacanimal/grohe-api:latest

    - name: Push the image to Docker Hub
      run: docker push pacanimal/grohe-api:latest
